baseURL: "https://xennis.github.io/wissenssammler"
indexes:
  tag: "tags"
languageCode: "de-de"
theme: "bleak"
title: "Wissenssammler"

params:
  cover: "images/cover.jpg"
  Subtitle: "Wissen ist Macht."
