baseURL: "https://xennis.github.io/wissenssammler"
indexes:
  tag: "tags"
languageCode: "de-de"
theme: "creative-portfolio"
title: "Wissenssammler"

params:
  # create-portfolio theme:
  style: "sea"
  copyright: "Wissenssammler"
  sidebarAbout: ["Wissen ist Macht."]
  navlinks:
    - name: Home
      url: portfolio/
      home: true
    - name: Über
      url: ueber/
